version: "3.7"

volumes:
  grafana-data:    

services:
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
    external: true