version: "3.7"

services:
  mq:
    container_name: mq01
    restart: unless-stopped
    image: rabbitmq:3.11.24-management-alpine
    network_mode: bridge
    ports:
        - "8080:15672"
        - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
    volumes:
      - ./.custom-data:/var/lib/rabbitmq:rw
    logging:
      options:
        max-size: "1m"
        max-file: "3"