global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    
  # - job_name: 'cadvisor'
  #   static_configs:
  #   - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.1.250:30001']    

  # - job_name: 'app_example'
  #   static_configs:
  #   - targets: ['app_example:8080'] 
    #metrics_path: '/metrics'
    #metrics_path: '/prometheus'